
all: favourite_architecture

favourite_architecture:
	wget -O /tmp/chal.zip https://adworld.xctf.org.cn/media/uploads/task/c11db24e682f4d4d802f4a3ca9ca76b8.zip
	unzip /tmp/chal.zip
	rm /tmp/chal.zip
